spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    initialization-mode: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    ROOT: ERROR